name: postman
version: latest
version-script: cat $SNAPCRAFT_STAGE/version
summary: API Development Environment
description: |
  Postman is the complete toolchain for API developers, used by more than 3 million developers and 30000 companies worldwide. Postman makes working with APIs faster and easier by supporting developers at every stage of their workflow, and is available for Mac OS X, Windows, Linux and Chrome users.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386
 
parts:
  postman:
    after: [desktop-gtk2]
    plugin: dump
    source-type: tar
    source: 
      - on amd64: https://dl.pstmn.io/download/latest/linux64
      - on i386: https://dl.pstmn.io/download/latest/linux32
    build-packages:
     - jshon
    override-build: |
     mkdir $SNAPCRAFT_PART_INSTALL/usr/share/Postman
     mv app/* $SNAPCRAFT_PART_INSTALL/usr/share/Postman
     VERSION=$(cat $SNAPCRAFT_PART_INSTALL/usr/share/Postman/resources/app/package.json | jshon -e version | sed 's/\"//g')
     echo $VERSION > $SNAPCRAFT_STAGE/version
    stage:
     - usr/*
    stage-packages:
      - libasound2
      - libatomic1
      - libc++1
      - libgconf2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpulse0
      - libxss1
      - libxtst6
      - libdb5.3

  desktop:
    after: [postman]
    plugin: dump
    source: .
    override-build: |
     mkdir $SNAPCRAFT_PART_INSTALL/usr $SNAPCRAFT_PART_INSTALL/usr/share $SNAPCRAFT_PART_INSTALL/usr/share/applications
     mv postman.desktop $SNAPCRAFT_PART_INSTALL/usr/share/applications
    stage:
     - usr/share/applications/postman.desktop
 
apps:
  postman:
    command: bin/desktop-launch $SNAP/usr/share/Postman/Postman
    desktop: usr/share/applications/postman.desktop
    plugs: [home, network, network-observe, x11, wayland, opengl, desktop, desktop-legacy, unity7, gsettings, browser-support]
